---
name: ads130e08
description: Driver for ADS130E08 ADC
version: 1.0.0
groups:
  - adc-dac
code_owners: weslleymfd
depends:
  - driver
  - log
thread_safe: yes
targets:
  - esp32
  - esp32s3
  - esp32s2
  - esp32c3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: MIT
copyrights:
  - name: weslleymfd
    year: 2021
