---
name: example
description: An example component
version: 0.0.1
groups:
  - misc
code_owners: trombik
depends:
  - driver
  - log
thread_safe: n/a
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: ISC
copyrights:
  - name: trombik
    year: 2021
