---
name: tca6424a
description: Driver for TCA6424A low-voltage 24-bit I2C I/O expander
version: 1.0.0
groups:
  - gpio
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2023
