name: pca9632
description: Driver for PCA9632 4-channel PWM chip
version: 1.0.0
groups:
  - led
code_owners: 
  - qb4-dev
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: qb4-dev
    year: 2024

