---
name: ina3221
description: Driver for INA3221 shunt and bus voltage monitor
version: 1.1.0
groups:
  - current
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: MIT
copyrights:
  - name: Zaltora
    year: 2016
  - name: UncleRus
    year: 2019
