---
name: hd44780
description: Driver for HD44780 compatible LCD text displays
version: 1.2.0
groups:
  - misc
code_owners:
  - UncleRus
depends:
  - driver
thread_safe: no
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2016
