---
name: ds1302
description: Driver for DS1302 RTC module
version: 1.1.0
groups:
  - rtc
code_owners:
  - UncleRus
depends:
  - log
  - esp_idf_lib_helpers
  - freertos
  - driver
thread_safe: no
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: PavelM
    year: 2016
  - name: UncleRus
    year: 2021
