---
name: calibration
description: Multi-point calibration library
version: 0.1.0
groups:
  - common
code_owners:
  - UncleRus
depends:
  - log
thread_safe: n/a
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2023
